### ISSUE TITLE
Getting "NoClassDefFound" error

### ISSUE THREAD

**Issue by aroc725** [adamtornhill/code-maat#70]
Using: Java 8, Leiningen 2.9.2

When I try to run the following command

java -jar C:\\code-maat\\target\\code-maat-1.1-SNAPSHOT.jar -l logfile.log -c git

I get the following error message:

Exception in thread "main" java.lang.NoClassDefFoundError: clojure/lang/Var
        at code_maat.cmd_line.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: clojure.lang.Var
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

I still get the error message above after running the following command: 

java -jar C:\\code-maat\\target\\code-maat-1.1-SNAPSHOT.jar -cp .;C:\Users\Owner\Documents\WindowsPowerShell\Modules\ClojureTools\clojure-tools-1.10.1.561.jar -l logfile.log -c git

**Comment by aroc725** [comment]
I still haven't figured out why the commands I originally tried don't work, but running the 'lein' script does work for me. So I'm going to close out this issue.
